name: smart_bitrix24
description: Smart Bitrix24 - Aplicativo Flutter com integração Bitrix24, modo offline e sincronização segura.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.2
  flutter_secure_storage: ^9.2.2
  sqflite: ^2.3.3+1
  path: ^1.9.0
  connectivity_plus: ^6.1.0
  flutter_riverpod: ^2.5.1
  url_launcher: ^6.3.0
  uni_links: ^0.5.1
  uuid: ^4.5.1
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  json_serializable: ^6.9.0

flutter:
  uses-material-design: true
  assets:
    - assets/